trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - script: |
        #!/bin/bash
        curl -O https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
        unzip terraform_1.0.11_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
      displayName: 'Install Terraform'

    - script: |
        terraform --version
        terraform init
        terraform plan
      displayName: 'Terraform Init and Plan'

# - stage: Deploy
#   displayName: 'Terraform Apply'
#   jobs:
#   - job: TerraformApply
#     displayName: 'Terraform Apply'
#     steps:
#     - script: |
#         #!/bin/bash
#         curl -O https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
#         unzip terraform_1.0.11_linux_amd64.zip
#         sudo mv terraform /usr/local/bin/
#       displayName: 'Install Terraform'

#     - script: |
#         terraform --version
#         terraform init -backend-config="storage_account_name=$(storageAccountName)" -backend-config="container_name=$(containerName)" -backend-config="key=$(key)" -backend-config="access_key=$(accessKey)"
#         terraform apply -auto-approve tfplan
#       displayName: 'Terraform Init and Apply'